### ISSUE TITLE
SSLCertVerificationError

### ISSUE THREAD

**Issue by thierionvi** [cusicand/lidarhd_ign_downloader#3]
Hi,

thank you for your very useful work !

I got the following error on a cluster with proxy :
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)

I just add this code at the beginning of the lidar_downloader.py :
```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

Vincent

**Comment by cusicand** [comment]
Dear Vincent,

Thank you for your comment.
Please refer to the [Release 3.0](https://github.com/cusicand/lidarhd_ign_downloader/releases/tag/v3.0) for new features regarding multi-threading and point density map generation.
In addition, due to the restricted access to the tile database, there is now an alternative download link to ensure the functionality of this tool.

Best wishes
Diego
